version: '3.8'

services:

  backend:
    image: eranda24/kochchi_app:${IMAGE_TAG:-latest}
    container_name: backend
    restart: always
    env_file:
      - .env
    depends_on:
      - mongodb
    networks:
      - internal

  mongodb:
    image: mongo:7.0
    container_name: mongodb
    command: mongod --auth --bind_ip_all
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: superadmin
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal
    ports:
      - "37017:27017"  # ðŸ‘ˆ External port 37017 â†’ internal 27017

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-entrypoint.sh:/docker-entrypoint.d/99-wait-for-cert.sh
      - certbot-etc:/etc/letsencrypt:ro
      - certbot-webroot:/var/lib/letsencrypt
    depends_on:
      - certbot
      - backend
    networks:
      - internal

  certbot:
    image: certbot/certbot
    container_name: certbot
    entrypoint: >
      /bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!};
      certbot renew --webroot -w /var/lib/letsencrypt; done'
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-webroot:/var/lib/letsencrypt
    networks:
      - internal

volumes:
  mongodb_data:
  certbot-webroot:
  certbot-etc:
    external: true

networks:
  internal:
